import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	// Performance optimizations
	metafile: prod,  // Generate build analysis in production
	ignoreAnnotations: prod,  // Ignore /* @__PURE__ */ annotations in prod
	legalComments: prod ? 'none' : 'inline',  // Remove comments in prod
	define: {
		'SMARTMP_ENV': prod ? '"production"' : '"development"'
	},
	loader: {
		".css": "text"
	},
	// Optimization: mark side-effect-free packages
	mainFields: ['module', 'main'],
});

if (prod) {
	const result = await context.rebuild();
	// Write metafile for bundle analysis
	if (result.metafile) {
		fs.writeFileSync('esbuild-meta.json', JSON.stringify(result.metafile, null, 2));
		console.log('Build meta written to esbuild-meta.json');
	}
	process.exit(0);
} else {
	await context.watch();
}
